"use client";
import { useState } from "react";
import { apiGet } from "@/lib/api";
import { FileText, Copy, Download, Mail, ChevronDown, ChevronUp, CheckCircle } from "lucide-react";
import { Button } from "@/components/ui/Button";

interface TripBriefProps {
  tripId: string;
}

function formatDate(d: string) {
  return new Date(d).toLocaleDateString("en", { weekday: "short", month: "long", day: "numeric", year: "numeric" });
}

function buildBriefText(data: any): string {
  const { trip, activitiesByDay, checklist, expenses, totalExpenses, members } = data;
  const days = Math.max(1, Math.round((new Date(trip.end_date).getTime() - new Date(trip.start_date).getTime()) / 86400000) + 1);

  let text = `✈️ TRIP BRIEF: ${trip.title.toUpperCase()}\n`;
  text += `${"=".repeat(50)}\n\n`;
  text += `📍 Destination: ${trip.destination}\n`;
  text += `📅 Dates: ${formatDate(trip.start_date)} – ${formatDate(trip.end_date)} (${days} days)\n`;
  text += `📊 Status: ${trip.status}\n`;
  if (trip.budget_amount) text += `💰 Budget: ${trip.currency} ${trip.budget_amount.toLocaleString()}\n`;
  if (trip.notes) text += `📝 Notes: ${trip.notes}\n`;
  text += `\n`;

  // Members
  if (members.length > 0) {
    text += `👥 TRAVELERS (${members.length})\n`;
    text += `${"-".repeat(30)}\n`;
    members.forEach((m: any) => { text += `  • ${m.name}${m.email ? ` (${m.email})` : ""}\n`; });
    text += `\n`;
  }

  // Itinerary
  const sortedDays = Object.keys(activitiesByDay).sort();
  if (sortedDays.length > 0) {
    text += `🗓️  DAY-BY-DAY ITINERARY\n`;
    text += `${"-".repeat(30)}\n`;
    sortedDays.forEach((day, idx) => {
      const acts = activitiesByDay[day];
      text += `\nDay ${idx + 1} — ${formatDate(day)}\n`;
      acts.forEach((a: any) => {
        text += `  [${a.start_time || "—"}] ${a.title}`;
        if (a.location) text += ` @ ${a.location}`;
        if (a.cost > 0) text += ` ($${a.cost})`;
        text += `\n`;
        if (a.description) text += `         ${a.description}\n`;
      });
    });
    text += `\n`;
  }

  // Packing checklist
  if (checklist.length > 0) {
    text += `🎒 PACKING CHECKLIST\n`;
    text += `${"-".repeat(30)}\n`;
    const categories: Record<string, any[]> = {};
    checklist.forEach((item: any) => {
      if (!categories[item.category]) categories[item.category] = [];
      categories[item.category].push(item);
    });
    Object.entries(categories).forEach(([cat, items]) => {
      text += `\n  ${cat.toUpperCase()}\n`;
      items.forEach((i: any) => { text += `  ${i.checked ? "[x]" : "[ ]"} ${i.text}\n`; });
    });
    text += `\n`;
  }

  // Expenses
  if (expenses.length > 0) {
    text += `💸 EXPENSES\n`;
    text += `${"-".repeat(30)}\n`;
    expenses.forEach((e: any) => {
      text += `  ${e.date} — ${e.title}: ${e.currency} ${e.amount} (paid by ${e.paid_by_name})\n`;
    });
    text += `\nTotal: ${trip.currency} ${totalExpenses.toLocaleString()}\n\n`;
  }

  // Emergency contacts placeholder
  text += `🆘 EMERGENCY CONTACTS\n`;
  text += `${"-".repeat(30)}\n`;
  text += `  Local Emergency: 112 / 911\n`;
  text += `  Embassy: [Add your country's embassy number]\n`;
  text += `  Travel Insurance: [Add your policy number & contact]\n`;
  text += `  Hotel: [Add hotel contact]\n\n`;

  text += `${"=".repeat(50)}\n`;
  text += `Generated by TripLog on ${new Date().toLocaleDateString("en", { month: "long", day: "numeric", year: "numeric" })}\n`;

  return text;
}

export function TripBrief({ tripId }: TripBriefProps) {
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [data, setData] = useState<any>(null);
  const [copied, setCopied] = useState(false);

  async function loadBrief() {
    if (data) { setOpen(o => !o); return; }
    setLoading(true);
    try {
      const d = await apiGet<any>(`/api/trips/${tripId}/brief`);
      setData(d);
      setOpen(true);
    } catch (err: any) {
      alert("Failed to load brief: " + err.message);
    } finally {
      setLoading(false);
    }
  }

  async function copyToClipboard() {
    if (!data) return;
    await navigator.clipboard.writeText(buildBriefText(data));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function downloadTxt() {
    if (!data) return;
    const text = buildBriefText(data);
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${data.trip.title.replace(/\s+/g, "-")}-brief.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function openEmailDraft() {
    if (!data) return;
    const subject = encodeURIComponent(`Trip Brief: ${data.trip.title}`);
    const body = encodeURIComponent(buildBriefText(data));
    window.open(`mailto:?subject=${subject}&body=${body}`);
  }

  return (
    <div className="bg-white rounded-2xl border border-[#e2e8f0] overflow-hidden shadow-sm">
      <button
        onClick={loadBrief}
        className="w-full flex items-center justify-between px-5 py-4 hover:bg-[#f8faff] transition-colors group"
      >
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-xl bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center">
            <FileText size={14} className="text-white" />
          </div>
          <div className="text-left">
            <p className="text-[#1e2044] font-semibold text-sm">Trip Brief</p>
            <p className="text-[#94a3b8] text-xs">Generate a shareable trip summary</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          {loading && <div className="w-4 h-4 border-2 border-[#e2e8f0] border-t-indigo-500 rounded-full animate-spin" />}
          {open ? <ChevronUp size={16} className="text-[#94a3b8]" /> : <ChevronDown size={16} className="text-[#94a3b8]" />}
        </div>
      </button>

      {open && data && (
        <div className="border-t border-[#e2e8f0]">
          {/* Action buttons */}
          <div className="px-5 py-3 flex items-center gap-2 flex-wrap border-b border-[#e2e8f0]">
            <Button variant="secondary" size="sm" onClick={copyToClipboard}>
              {copied ? <CheckCircle size={13} className="text-green-500" /> : <Copy size={13} />}
              {copied ? "Copied!" : "Copy"}
            </Button>
            <Button variant="secondary" size="sm" onClick={downloadTxt}>
              <Download size={13} />Download .txt
            </Button>
            <Button variant="secondary" size="sm" onClick={openEmailDraft}>
              <Mail size={13} />Email Draft
            </Button>
          </div>

          {/* Preview */}
          <div className="px-5 py-4 space-y-5 max-h-[600px] overflow-y-auto">
            {/* Header */}
            <div className="space-y-1">
              <h3 className="text-xl font-bold text-[#1e2044]">{data.trip.title}</h3>
              <p className="text-indigo-600 text-sm font-medium">📍 {data.trip.destination}</p>
              <div className="flex flex-wrap gap-3 text-[#64748b] text-xs mt-2">
                <span>📅 {formatDate(data.trip.start_date)} – {formatDate(data.trip.end_date)}</span>
                {data.trip.budget_amount && <span>💰 {data.trip.currency} {data.trip.budget_amount.toLocaleString()}</span>}
              </div>
            </div>

            {/* Travelers */}
            {data.members.length > 0 && (
              <div className="space-y-2">
                <h4 className="text-xs font-semibold text-[#94a3b8] uppercase tracking-wider">Travelers</h4>
                <div className="flex flex-wrap gap-2">
                  {data.members.map((m: any, i: number) => (
                    <span key={i} className="text-xs px-2.5 py-1 rounded-full bg-indigo-100 text-indigo-700 border border-indigo-200">
                      {m.name}
                    </span>
                  ))}
                </div>
              </div>
            )}

            {/* Itinerary preview */}
            {Object.keys(data.activitiesByDay).length > 0 && (
              <div className="space-y-3">
                <h4 className="text-xs font-semibold text-[#94a3b8] uppercase tracking-wider">Itinerary</h4>
                {Object.entries(data.activitiesByDay as Record<string, any[]>)
                  .sort(([a], [b]) => a.localeCompare(b))
                  .map(([day, acts], idx) => (
                    <div key={day} className="space-y-1">
                      <p className="text-[#64748b] text-xs font-medium">Day {idx + 1} — {formatDate(day)}</p>
                      <div className="space-y-1 pl-3 border-l border-[#e2e8f0]">
                        {acts.map((a: any) => (
                          <div key={a.id} className="text-sm text-[#64748b]">
                            {a.start_time && <span className="text-[#94a3b8] mr-2">{a.start_time}</span>}
                            {a.title}
                            {a.location && <span className="text-[#94a3b8] text-xs ml-1">@ {a.location}</span>}
                          </div>
                        ))}
                      </div>
                    </div>
                  ))}
              </div>
            )}

            {/* Checklist summary */}
            {data.checklist.length > 0 && (
              <div className="space-y-2">
                <h4 className="text-xs font-semibold text-[#94a3b8] uppercase tracking-wider">
                  Packing ({data.checklist.filter((i: any) => i.checked).length}/{data.checklist.length} packed)
                </h4>
                <div className="h-2 bg-[#e2e8f0] rounded-full overflow-hidden">
                  <div
                    className="h-full bg-gradient-to-r from-indigo-500 to-purple-600 rounded-full"
                    style={{ width: `${Math.round((data.checklist.filter((i: any) => i.checked).length / data.checklist.length) * 100)}%` }}
                  />
                </div>
              </div>
            )}

            {/* Expenses summary */}
            {data.expenses.length > 0 && (
              <div className="space-y-2">
                <h4 className="text-xs font-semibold text-[#94a3b8] uppercase tracking-wider">Expenses</h4>
                <p className="text-[#1e2044] font-bold text-lg">
                  {data.trip.currency} {data.totalExpenses.toLocaleString()}
                  <span className="text-[#94a3b8] text-sm font-normal ml-2">total across {data.expenses.length} entries</span>
                </p>
              </div>
            )}

            {/* Emergency contacts */}
            <div className="bg-red-50 rounded-xl p-4 space-y-2 border border-red-100">
              <h4 className="text-xs font-semibold text-red-500 uppercase tracking-wider">Emergency Contacts</h4>
              <p className="text-[#94a3b8] text-xs">Local Emergency: 112 / 911 · Add your embassy, insurance, and hotel contacts to the downloaded .txt file</p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
